apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2026-03-08T05:55:36Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "204"
    uid: 53df54f1-e55d-4489-a6ac-7cb41c41428f
  spec:
    clusterIP: 10.245.0.1
    clusterIPs:
    - 10.245.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: cilium
      meta.helm.sh/release-namespace: kube-system
      prometheus.io/port: "9964"
      prometheus.io/scrape: "true"
    creationTimestamp: "2026-03-08T05:55:50Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: cilium-envoy
      app.kubernetes.io/part-of: cilium
      io.cilium/app: proxy
      k8s-app: cilium-envoy
    name: cilium-envoy
    namespace: kube-system
    resourceVersion: "509"
    uid: bd50595c-4e02-440b-8c9e-9a1bce1154d4
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: envoy-metrics
      port: 9964
      protocol: TCP
      targetPort: 9964
    selector:
      k8s-app: cilium-envoy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: cilium
      meta.helm.sh/release-namespace: kube-system
    creationTimestamp: "2026-03-08T05:55:50Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: hubble-peer
      app.kubernetes.io/part-of: cilium
      k8s-app: cilium
    name: hubble-peer
    namespace: kube-system
    resourceVersion: "511"
    uid: 982c1c2b-6210-4a0d-a872-34f95c77f1b2
  spec:
    clusterIP: 10.245.150.24
    clusterIPs:
    - 10.245.150.24
    internalTrafficPolicy: Local
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: peer-service
      port: 443
      protocol: TCP
      targetPort: 4244
    selector:
      k8s-app: cilium
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "9153"
      prometheus.io/scrape: "true"
    creationTimestamp: "2026-03-08T05:55:37Z"
    labels:
      k8s-app: kube-dns
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: CoreDNS
    name: kube-dns
    namespace: kube-system
    resourceVersion: "254"
    uid: ae7b7dd8-605d-45cb-86e2-d466024770b1
  spec:
    clusterIP: 10.245.0.10
    clusterIPs:
    - 10.245.0.10
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
    selector:
      k8s-app: kube-dns
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
