apiVersion: v1
items:
- apiVersion: cilium.io/v2
  kind: CiliumEnvoyConfig
  metadata:
    annotations:
      cec.cilium.io/use-original-source-address: "false"
    creationTimestamp: "2026-03-08T02:57:01Z"
    generation: 1
    labels:
      gateway.networking.k8s.io/gateway-name: all-namespaces
    name: cilium-gateway-all-namespaces
    namespace: gateway-conformance-infra
    ownerReferences:
    - apiVersion: gateway.networking.k8s.io/v1
      controller: true
      kind: Gateway
      name: all-namespaces
      uid: 763cd589-31ff-42cf-8580-61e2f225d290
    resourceVersion: "914"
    uid: 5daeda5d-c125-41f6-8161-185ea6cba2b5
  spec:
    resources:
    - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
      filterChains:
      - filterChainMatch:
          transportProtocol: raw_buffer
        filters:
        - name: envoy.filters.network.http_connection_manager
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            commonHttpProtocolOptions:
              maxStreamDuration: 0s
            httpFilters:
            - name: envoy.filters.http.grpc_web
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
            - name: envoy.filters.http.grpc_stats
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
                emitFilterState: true
                enableUpstreamStats: true
            - name: envoy.filters.http.router
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
            internalAddressConfig:
              cidrRanges:
              - addressPrefix: 10.0.0.0
                prefixLen: 8
              - addressPrefix: 172.16.0.0
                prefixLen: 12
              - addressPrefix: 192.168.0.0
                prefixLen: 16
              - addressPrefix: 127.0.0.1
                prefixLen: 32
            rds:
              routeConfigName: listener-insecure
            statPrefix: listener-insecure
            streamIdleTimeout: 300s
            upgradeConfigs:
            - upgradeType: websocket
            useRemoteAddress: true
      listenerFilters:
      - name: envoy.filters.listener.tls_inspector
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
      name: listener
      socketOptions:
      - description: Enable TCP keep-alive (default to enabled)
        intValue: "1"
        level: "1"
        name: "9"
      - description: TCP keep-alive idle time (in seconds) (defaults to 10s)
        intValue: "10"
        level: "6"
        name: "4"
      - description: TCP keep-alive probe intervals (in seconds) (defaults to 5s)
        intValue: "5"
        level: "6"
        name: "5"
      - description: TCP keep-alive probe max failures.
        intValue: "10"
        level: "6"
        name: "6"
    - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: listener-insecure
    services:
    - name: cilium-gateway-all-namespaces
      namespace: gateway-conformance-infra
      ports:
      - 80
- apiVersion: cilium.io/v2
  kind: CiliumEnvoyConfig
  metadata:
    annotations:
      cec.cilium.io/use-original-source-address: "false"
    creationTimestamp: "2026-03-08T02:57:01Z"
    generation: 1
    labels:
      gateway.networking.k8s.io/gateway-name: backend-namespaces
    name: cilium-gateway-backend-namespaces
    namespace: gateway-conformance-infra
    ownerReferences:
    - apiVersion: gateway.networking.k8s.io/v1
      controller: true
      kind: Gateway
      name: backend-namespaces
      uid: 22b177ef-9d22-4e70-abbe-628819f249ec
    resourceVersion: "949"
    uid: b7c0ace3-07f9-4ef7-929a-19d119d0c121
  spec:
    resources:
    - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
      filterChains:
      - filterChainMatch:
          transportProtocol: raw_buffer
        filters:
        - name: envoy.filters.network.http_connection_manager
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            commonHttpProtocolOptions:
              maxStreamDuration: 0s
            httpFilters:
            - name: envoy.filters.http.grpc_web
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
            - name: envoy.filters.http.grpc_stats
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
                emitFilterState: true
                enableUpstreamStats: true
            - name: envoy.filters.http.router
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
            internalAddressConfig:
              cidrRanges:
              - addressPrefix: 10.0.0.0
                prefixLen: 8
              - addressPrefix: 172.16.0.0
                prefixLen: 12
              - addressPrefix: 192.168.0.0
                prefixLen: 16
              - addressPrefix: 127.0.0.1
                prefixLen: 32
            rds:
              routeConfigName: listener-insecure
            statPrefix: listener-insecure
            streamIdleTimeout: 300s
            upgradeConfigs:
            - upgradeType: websocket
            useRemoteAddress: true
      listenerFilters:
      - name: envoy.filters.listener.tls_inspector
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
      name: listener
      socketOptions:
      - description: Enable TCP keep-alive (default to enabled)
        intValue: "1"
        level: "1"
        name: "9"
      - description: TCP keep-alive idle time (in seconds) (defaults to 10s)
        intValue: "10"
        level: "6"
        name: "4"
      - description: TCP keep-alive probe intervals (in seconds) (defaults to 5s)
        intValue: "5"
        level: "6"
        name: "5"
      - description: TCP keep-alive probe max failures.
        intValue: "10"
        level: "6"
        name: "6"
    - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: listener-insecure
    services:
    - name: cilium-gateway-backend-namespaces
      namespace: gateway-conformance-infra
      ports:
      - 80
- apiVersion: cilium.io/v2
  kind: CiliumEnvoyConfig
  metadata:
    annotations:
      cec.cilium.io/use-original-source-address: "false"
    creationTimestamp: "2026-03-08T02:57:01Z"
    generation: 7
    labels:
      gateway.networking.k8s.io/gateway-name: same-namespace
    name: cilium-gateway-same-namespace
    namespace: gateway-conformance-infra
    ownerReferences:
    - apiVersion: gateway.networking.k8s.io/v1
      controller: true
      kind: Gateway
      name: same-namespace
      uid: 6c3a6244-dd22-49ff-ac6b-7fdd31217c8e
    resourceVersion: "1749"
    uid: b7f2af36-2a02-4da4-b63a-6e18260e2a5a
  spec:
    resources:
    - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
      filterChains:
      - filterChainMatch:
          transportProtocol: raw_buffer
        filters:
        - name: envoy.filters.network.http_connection_manager
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            commonHttpProtocolOptions:
              maxStreamDuration: 0s
            httpFilters:
            - name: envoy.filters.http.grpc_web
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
            - name: envoy.filters.http.grpc_stats
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
                emitFilterState: true
                enableUpstreamStats: true
            - name: envoy.filters.http.router
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
            internalAddressConfig:
              cidrRanges:
              - addressPrefix: 10.0.0.0
                prefixLen: 8
              - addressPrefix: 172.16.0.0
                prefixLen: 12
              - addressPrefix: 192.168.0.0
                prefixLen: 16
              - addressPrefix: 127.0.0.1
                prefixLen: 32
            rds:
              routeConfigName: listener-insecure
            statPrefix: listener-insecure
            streamIdleTimeout: 300s
            upgradeConfigs:
            - upgradeType: websocket
            useRemoteAddress: true
      listenerFilters:
      - name: envoy.filters.listener.tls_inspector
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
      name: listener
      socketOptions:
      - description: Enable TCP keep-alive (default to enabled)
        intValue: "1"
        level: "1"
        name: "9"
      - description: TCP keep-alive idle time (in seconds) (defaults to 10s)
        intValue: "10"
        level: "6"
        name: "4"
      - description: TCP keep-alive probe intervals (in seconds) (defaults to 5s)
        intValue: "5"
        level: "6"
        name: "5"
      - description: TCP keep-alive probe max failures.
        intValue: "10"
        level: "6"
        name: "6"
    - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: listener-insecure
    services:
    - name: cilium-gateway-same-namespace
      namespace: gateway-conformance-infra
      ports:
      - 80
- apiVersion: cilium.io/v2
  kind: CiliumEnvoyConfig
  metadata:
    annotations:
      cec.cilium.io/use-original-source-address: "false"
    creationTimestamp: "2026-03-08T02:57:01Z"
    generation: 1
    labels:
      gateway.networking.k8s.io/gateway-name: same-namespace-with-https-listener
    name: cilium-gateway-same-namespace-with-https-listener
    namespace: gateway-conformance-infra
    ownerReferences:
    - apiVersion: gateway.networking.k8s.io/v1
      controller: true
      kind: Gateway
      name: same-namespace-with-https-listener
      uid: 63418213-1cc8-458a-9589-b5928755fee9
    resourceVersion: "1091"
    uid: 2d3ef098-5f0d-46d0-b273-1865b07e36c3
  spec:
    resources:
    - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
      filterChains:
      - filterChainMatch:
          transportProtocol: raw_buffer
        filters:
        - name: envoy.filters.network.http_connection_manager
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            commonHttpProtocolOptions:
              maxStreamDuration: 0s
            httpFilters:
            - name: envoy.filters.http.grpc_web
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
            - name: envoy.filters.http.grpc_stats
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
                emitFilterState: true
                enableUpstreamStats: true
            - name: envoy.filters.http.router
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
            internalAddressConfig:
              cidrRanges:
              - addressPrefix: 10.0.0.0
                prefixLen: 8
              - addressPrefix: 172.16.0.0
                prefixLen: 12
              - addressPrefix: 192.168.0.0
                prefixLen: 16
              - addressPrefix: 127.0.0.1
                prefixLen: 32
            rds:
              routeConfigName: listener-insecure
            statPrefix: listener-insecure
            streamIdleTimeout: 300s
            upgradeConfigs:
            - upgradeType: websocket
            useRemoteAddress: true
      - filterChainMatch:
          transportProtocol: tls
        filters:
        - name: envoy.filters.network.http_connection_manager
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            commonHttpProtocolOptions:
              maxStreamDuration: 0s
            httpFilters:
            - name: envoy.filters.http.grpc_web
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
            - name: envoy.filters.http.grpc_stats
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
                emitFilterState: true
                enableUpstreamStats: true
            - name: envoy.filters.http.router
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
            internalAddressConfig:
              cidrRanges:
              - addressPrefix: 10.0.0.0
                prefixLen: 8
              - addressPrefix: 172.16.0.0
                prefixLen: 12
              - addressPrefix: 192.168.0.0
                prefixLen: 16
              - addressPrefix: 127.0.0.1
                prefixLen: 32
            rds:
              routeConfigName: listener-secure
            statPrefix: listener-secure
            streamIdleTimeout: 300s
            upgradeConfigs:
            - upgradeType: websocket
            useRemoteAddress: true
        transportSocket:
          name: envoy.transport_sockets.tls
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            commonTlsContext:
              tlsCertificateSdsSecretConfigs:
              - name: cilium-secrets/gateway-conformance-infra-tls-validity-checks-certificate
      listenerFilters:
      - name: envoy.filters.listener.tls_inspector
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
      name: listener
      socketOptions:
      - description: Enable TCP keep-alive (default to enabled)
        intValue: "1"
        level: "1"
        name: "9"
      - description: TCP keep-alive idle time (in seconds) (defaults to 10s)
        intValue: "10"
        level: "6"
        name: "4"
      - description: TCP keep-alive probe intervals (in seconds) (defaults to 5s)
        intValue: "5"
        level: "6"
        name: "5"
      - description: TCP keep-alive probe max failures.
        intValue: "10"
        level: "6"
        name: "6"
    - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: listener-insecure
    - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: listener-secure
    services:
    - name: cilium-gateway-same-namespace-with-https-listener
      namespace: gateway-conformance-infra
      ports:
      - 443
kind: List
metadata:
  resourceVersion: ""
